# Generated by Django 4.0 on 2021-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_type_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], default='income', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], default='income', max_length=32),
        ),
    ]
